name = "Jjama3"
uuid = "1285d783-1a6d-4703-8f05-8ac83ef55592"
authors = ["murrellb <murrellb@gmail.com> and contributors"]
version = "1.1.0-DEV"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HuggingFaceTokenizers = "a6888d44-1185-43bb-bd0f-7806f9976d18"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogitSamplers = "1b30fcfc-0ee9-4be2-9cfe-b2289b43e041"
LowRankLayers = "b66182ab-a85c-43b0-99bd-d85cc47c5e50"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
ReactantCore = "a3311ec8-5e00-46d5-b541-4f83e724a433"
SafeTensors = "eeda0dda-7046-4914-a807-2495fc7abb89"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"

[sources]
HuggingFaceTokenizers = {rev = "main", url = "https://github.com/MurrellGroup/HuggingFaceTokenizers.jl"}
LowRankLayers = {rev = "main", url = "https://github.com/MurrellGroup/LowRankLayers.jl"}

[extensions]
MetalExt = "Metal"

[compat]
Accessors = "0.1.38"
Distributions = "0.25"
Flux = "0.14"
LogitSamplers = "0.1"
LowRankLayers = "0.1"
Metal = "1"
NNlib = "0.9"
ReactantCore = "0.1.2"
SafeTensors = "1"
StatsBase = "0.34"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
